/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        tab: {
            name: 'Tab', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, Stepper: {
                    name: "Stepper",
                    type: "Stepper",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'tab',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        stepper: {
            name: 'Stepper', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, tab: {
                    name: "tab",
                    type: "Tab",
                    isDataModel: true,
                    backLink: 'Stepper',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "tabId" },
                }, tabId: {
                    name: "tabId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'tab',
                }, from: {
                    name: "from",
                    type: "String",
                }, to: {
                    name: "to",
                    type: "String",
                }, value: {
                    name: "value",
                    type: "Float",
                }, data: {
                    name: "data",
                    type: "String",
                }, gasLimit: {
                    name: "gasLimit",
                    type: "Int",
                }, gasPrice: {
                    name: "gasPrice",
                    type: "Int",
                }, Transaction: {
                    name: "Transaction",
                    type: "Transaction",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'stepper',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        transaction: {
            name: 'Transaction', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, stepper: {
                    name: "stepper",
                    type: "Stepper",
                    isDataModel: true,
                    backLink: 'Transaction',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "stepperId" },
                }, stepperId: {
                    name: "stepperId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'stepper',
                }, hash: {
                    name: "hash",
                    type: "String",
                }, gasUsed: {
                    name: "gasUsed",
                    type: "Int",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, hash: {
                    name: "hash",
                    fields: ["hash"]
                },
            },
        },

    },
    deleteCascade: {

    },

};
export default metadata;
