/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

export * from './scan-wallet'
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5'
export { Provider } from '@zenstackhq/tanstack-query/runtime-v5/react'
export { default as metadata } from './__model_meta'
