const MULTICALL_ABI = [
    { type: 'receive', stateMutability: 'payable' },
    {
        type: 'function',
        name: 'aggregate',
        inputs: [
            { name: 'targets', type: 'address[]', internalType: 'address[]' },
            { name: 'calls', type: 'bytes[]', internalType: 'bytes[]' },
            { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
            { name: 'strict', type: 'bool', internalType: 'bool' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'approve',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'spender', type: 'address', internalType: 'address' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
] as any[]

const ROUTER_PANCAKE_V2_ABI = [
    {
        type: 'function',
        name: 'WETH',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'addLiquidity',
        inputs: [
            { name: 'tokenA', type: 'address', internalType: 'address' },
            { name: 'tokenB', type: 'address', internalType: 'address' },
            {
                name: 'amountADesired',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountBDesired',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'amountAMin', type: 'uint256', internalType: 'uint256' },
            { name: 'amountBMin', type: 'uint256', internalType: 'uint256' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [
            { name: 'amountA', type: 'uint256', internalType: 'uint256' },
            { name: 'amountB', type: 'uint256', internalType: 'uint256' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'addLiquidityETH',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            {
                name: 'amountTokenDesired',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountTokenMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountETHMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [
            { name: 'amountToken', type: 'uint256', internalType: 'uint256' },
            { name: 'amountETH', type: 'uint256', internalType: 'uint256' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'factory',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'getAmountIn',
        inputs: [
            { name: 'amountOut', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveIn', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveOut', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amountIn', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'getAmountOut',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveIn', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveOut', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amountOut', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'getAmountsIn',
        inputs: [
            { name: 'amountOut', type: 'uint256', internalType: 'uint256' },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'getAmountsOut',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'quote',
        inputs: [
            { name: 'amountA', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveA', type: 'uint256', internalType: 'uint256' },
            { name: 'reserveB', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amountB', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'removeLiquidity',
        inputs: [
            { name: 'tokenA', type: 'address', internalType: 'address' },
            { name: 'tokenB', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            { name: 'amountAMin', type: 'uint256', internalType: 'uint256' },
            { name: 'amountBMin', type: 'uint256', internalType: 'uint256' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [
            { name: 'amountA', type: 'uint256', internalType: 'uint256' },
            { name: 'amountB', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'removeLiquidityETH',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountTokenMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountETHMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [
            { name: 'amountToken', type: 'uint256', internalType: 'uint256' },
            { name: 'amountETH', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'removeLiquidityETHSupportingFeeOnTransferTokens',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountTokenMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountETHMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amountETH', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'removeLiquidityETHWithPermit',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountTokenMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountETHMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
            { name: 'approveMax', type: 'bool', internalType: 'bool' },
            { name: 'v', type: 'uint8', internalType: 'uint8' },
            { name: 'r', type: 'bytes32', internalType: 'bytes32' },
            { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
        outputs: [
            { name: 'amountToken', type: 'uint256', internalType: 'uint256' },
            { name: 'amountETH', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'removeLiquidityETHWithPermitSupportingFeeOnTransferTokens',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountTokenMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            {
                name: 'amountETHMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
            { name: 'approveMax', type: 'bool', internalType: 'bool' },
            { name: 'v', type: 'uint8', internalType: 'uint8' },
            { name: 'r', type: 'bytes32', internalType: 'bytes32' },
            { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
        outputs: [{ name: 'amountETH', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'removeLiquidityWithPermit',
        inputs: [
            { name: 'tokenA', type: 'address', internalType: 'address' },
            { name: 'tokenB', type: 'address', internalType: 'address' },
            { name: 'liquidity', type: 'uint256', internalType: 'uint256' },
            { name: 'amountAMin', type: 'uint256', internalType: 'uint256' },
            { name: 'amountBMin', type: 'uint256', internalType: 'uint256' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
            { name: 'approveMax', type: 'bool', internalType: 'bool' },
            { name: 'v', type: 'uint8', internalType: 'uint8' },
            { name: 'r', type: 'bytes32', internalType: 'bytes32' },
            { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
        outputs: [
            { name: 'amountA', type: 'uint256', internalType: 'uint256' },
            { name: 'amountB', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapETHForExactTokens',
        inputs: [
            { name: 'amountOut', type: 'uint256', internalType: 'uint256' },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'swapExactETHForTokens',
        inputs: [
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'swapExactETHForTokensSupportingFeeOnTransferTokens',
        inputs: [
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'swapExactTokensForETH',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapExactTokensForETHSupportingFeeOnTransferTokens',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapExactTokensForTokens',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapExactTokensForTokensSupportingFeeOnTransferTokens',
        inputs: [
            { name: 'amountIn', type: 'uint256', internalType: 'uint256' },
            {
                name: 'amountOutMin',
                type: 'uint256',
                internalType: 'uint256',
            },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapTokensForExactETH',
        inputs: [
            { name: 'amountOut', type: 'uint256', internalType: 'uint256' },
            { name: 'amountInMax', type: 'uint256', internalType: 'uint256' },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'swapTokensForExactTokens',
        inputs: [
            { name: 'amountOut', type: 'uint256', internalType: 'uint256' },
            { name: 'amountInMax', type: 'uint256', internalType: 'uint256' },
            { name: 'path', type: 'address[]', internalType: 'address[]' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'deadline', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'nonpayable',
    },
]

const ERC20_ABI = [
    {
        type: 'function',
        name: 'allowance',
        inputs: [
            { name: 'owner', type: 'address', internalType: 'address' },
            { name: 'spender', type: 'address', internalType: 'address' },
        ],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'approve',
        inputs: [
            { name: 'spender', type: 'address', internalType: 'address' },
            { name: 'value', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'balanceOf',
        inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'decimals',
        inputs: [],
        outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'name',
        inputs: [],
        outputs: [{ name: '', type: 'string', internalType: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'symbol',
        inputs: [],
        outputs: [{ name: '', type: 'string', internalType: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'totalSupply',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'transfer',
        inputs: [
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'value', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'transferFrom',
        inputs: [
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'value', type: 'uint256', internalType: 'uint256' },
        ],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'event',
        name: 'Approval',
        inputs: [
            {
                name: 'owner',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'spender',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'value',
                type: 'uint256',
                indexed: false,
                internalType: 'uint256',
            },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'Transfer',
        inputs: [
            {
                name: 'from',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'to',
                type: 'address',
                indexed: true,
                internalType: 'address',
            },
            {
                name: 'value',
                type: 'uint256',
                indexed: false,
                internalType: 'uint256',
            },
        ],
        anonymous: false,
    },
    {
        type: 'error',
        name: 'ERC20InsufficientAllowance',
        inputs: [
            { name: 'spender', type: 'address', internalType: 'address' },
            { name: 'allowance', type: 'uint256', internalType: 'uint256' },
            { name: 'needed', type: 'uint256', internalType: 'uint256' },
        ],
    },
    {
        type: 'error',
        name: 'ERC20InsufficientBalance',
        inputs: [
            { name: 'sender', type: 'address', internalType: 'address' },
            { name: 'balance', type: 'uint256', internalType: 'uint256' },
            { name: 'needed', type: 'uint256', internalType: 'uint256' },
        ],
    },
    {
        type: 'error',
        name: 'ERC20InvalidApprover',
        inputs: [{ name: 'approver', type: 'address', internalType: 'address' }],
    },
    {
        type: 'error',
        name: 'ERC20InvalidReceiver',
        inputs: [{ name: 'receiver', type: 'address', internalType: 'address' }],
    },
    {
        type: 'error',
        name: 'ERC20InvalidSender',
        inputs: [{ name: 'sender', type: 'address', internalType: 'address' }],
    },
    {
        type: 'error',
        name: 'ERC20InvalidSpender',
        inputs: [{ name: 'spender', type: 'address', internalType: 'address' }],
    },
]

const FACTORY_PANCAKE_V2_ABI = [
    {
        inputs: [{ internalType: 'address', name: '_feeToSetter', type: 'address' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'token0',
                type: 'address',
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'token1',
                type: 'address',
            },
            {
                indexed: false,
                internalType: 'address',
                name: 'pair',
                type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: '', type: 'uint256' },
        ],
        name: 'PairCreated',
        type: 'event',
    },
    {
        constant: true,
        inputs: [],
        name: 'INIT_CODE_PAIR_HASH',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: true,
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'allPairs',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: true,
        inputs: [],
        name: 'allPairsLength',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: false,
        inputs: [
            { internalType: 'address', name: 'tokenA', type: 'address' },
            { internalType: 'address', name: 'tokenB', type: 'address' },
        ],
        name: 'createPair',
        outputs: [{ internalType: 'address', name: 'pair', type: 'address' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        constant: true,
        inputs: [],
        name: 'feeTo',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: true,
        inputs: [],
        name: 'feeToSetter',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: true,
        inputs: [
            { internalType: 'address', name: '', type: 'address' },
            { internalType: 'address', name: '', type: 'address' },
        ],
        name: 'getPair',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function',
    },
    {
        constant: false,
        inputs: [{ internalType: 'address', name: '_feeTo', type: 'address' }],
        name: 'setFeeTo',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        constant: false,
        inputs: [{ internalType: 'address', name: '_feeToSetter', type: 'address' }],
        name: 'setFeeToSetter',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function',
    },
]

const DISPERSE_ABI = [
    {
        type: 'function',
        name: 'disperseEther',
        inputs: [
            { name: 'recipients', type: 'address[]', internalType: 'address[]' },
            { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
        ],
        outputs: [],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'disperseToken',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'recipients', type: 'address[]', internalType: 'address[]' },
            { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'disperseTokenSimple',
        inputs: [
            { name: 'token', type: 'address', internalType: 'address' },
            { name: 'recipients', type: 'address[]', internalType: 'address[]' },
            { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
        ],
        outputs: [],
        stateMutability: 'nonpayable',
    },
] as any[]

export { MULTICALL_ABI, ROUTER_PANCAKE_V2_ABI, ERC20_ABI, FACTORY_PANCAKE_V2_ABI, DISPERSE_ABI }
