import { BrowserWindow, app, ipcMain, shell } from 'electron'
import fs from 'fs'
import path from 'path'
import { parse } from 'csv-parse/sync'
import { stringify } from 'csv-stringify/sync'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

const DATA_DIR = path.join(app.getPath('appData'), 'scan-tool')
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR)

function getCsvFile(sheetTitle: string) {
    return path.join(DATA_DIR, `${sheetTitle}.csv`)
}

function ensureSheetExists(sheetTitle: string) {
    const file = getCsvFile(sheetTitle)
    if (!fs.existsSync(file)) {
        fs.writeFileSync(file, '')
    }
}
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit()
}

let mainWindow: BrowserWindow

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        center: true,
        webPreferences: {
            contextIsolation: true,
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
        width: 1280,
        height: 720,
        icon: './src/favicon.ico',
    })

    mainWindow.setMenuBarVisibility(false)

    mainWindow.maximize()

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

    ipcMain.on('open-link', (event, url) => {
        shell.openExternal(url)
    })

    ipcMain.on('set-progress-bar', (event, value) => {
        mainWindow.setProgressBar(value)
    })

    ipcMain.handle('sheets:check', (event, wallet: string, tokenAddress: string) => {
        try {
            ensureSheetExists(tokenAddress)
            const file = getCsvFile(tokenAddress)
            const content = fs.readFileSync(file, 'utf8')
            const records = parse(content, { columns: false, skip_empty_lines: true })
            const addresses = records.map((row: any) => row[0]?.toLowerCase())
            const exists = addresses.includes(wallet.toLowerCase())
            return exists
        } catch (err: any) {
            console.error('CSV Error:', err.message)
            return true
        }
    })

    ipcMain.handle('sheets:read', (event, tokenAddress: string) => {
        try {
            ensureSheetExists(tokenAddress)
            const file = getCsvFile(tokenAddress)
            const content = fs.readFileSync(file, 'utf8')
            const records = parse(content, { columns: false, skip_empty_lines: true })
            const wallets = records
                .map((row: any) => ({
                    address: row[0]?.toLowerCase() || '',
                    balance: row[1] ? Number(row[1]) : 0,
                    tokens: row[2] ? JSON.parse(row[2]) : [],
                    airdropped: row[3]?.toLowerCase() === 'true',
                }))
                .filter((w: any) => !w.airdropped)
            return wallets
        } catch (err: any) {
            console.error('CSV Read Error:', err.message)
            return []
        }
    })

    ipcMain.handle('sheets:write', (event, tokenAddress: string, ...wallets: string[]) => {
        try {
            ensureSheetExists(tokenAddress)
            const file = getCsvFile(tokenAddress)
            const content = fs.readFileSync(file, 'utf8')
            const records = content
                ? parse(content, { columns: false, skip_empty_lines: true })
                : []
            let updated = false
            for (const walletCombined of wallets) {
                if (!walletCombined) continue
                const [wallet, balance, tokens, airdropped] = walletCombined.split(',')
                let found = false
                for (let i = 0; i < records.length; i++) {
                    if (records[i][0]?.toLowerCase() === wallet.toLowerCase()) {
                        records[i] = [wallet, balance, tokens, airdropped]
                        found = true
                        updated = true
                        break
                    }
                }
                if (!found) {
                    records.push([wallet, balance, tokens, airdropped])
                    updated = true
                }
            }
            if (updated) {
                const csv = stringify(records)
                fs.writeFileSync(file, csv)
            }
            return true
        } catch (err: any) {
            console.error('CSV Write Error:', err.message)
            return false
        }
    })

    ipcMain.handle(
        'sheets:writeBalance',
        (_event, wallet: string, token: string, balance: string) => {
            const today = new Date().toISOString().slice(0, 10)
            const sheetName = `Balance_${today}`
            ensureSheetExists(sheetName)
            try {
                const file = getCsvFile(sheetName)
                const content = fs.readFileSync(file, 'utf8')
                const records = content
                    ? parse(content, { columns: false, skip_empty_lines: true })
                    : []
                if (records.length === 0) {
                    records.push(['Wallet', token])
                }
                const headers = records[0]
                let tokenCol = headers.indexOf(token)
                if (tokenCol === -1) {
                    headers.push(token)
                    tokenCol = headers.length - 1
                }
                let rowIndex = records.findIndex((row, idx) => idx > 0 && row[0] === wallet)
                if (rowIndex === -1) {
                    rowIndex = records.length
                    const newRow = Array(headers.length).fill('')
                    newRow[0] = wallet
                    newRow[tokenCol] = balance
                    records.push(newRow)
                } else {
                    records[rowIndex][tokenCol] = balance
                }
                const csv = stringify(records)
                fs.writeFileSync(file, csv)
                return { success: true }
            } catch (err: any) {
                console.error('CSV WriteBalance Error:', err.message)
                return { success: false, error: err.message }
            }
        }
    )

    const ses = mainWindow.webContents.session
    ses.clearAuthCache()
    ses.clearCache()
    ses.clearHostResolverCache()
    mainWindow.webContents.clearHistory()
    // Open the DevTools.
    // mainWindow.webContents.openDevTools();
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow()
    }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
