import { BrowserWindow, app, dialog, ipcMain, shell } from 'electron'
import fs from 'fs'
import path from 'path'
import { PrismaClient } from './prisma/client'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string
const prisma = new PrismaClient({
    datasourceUrl: app.isPackaged ? `file:${path.join(app.getAppPath(), '..', 'scan-wallet.sqlite')}` : `file:${path.join(app.getAppPath(), 'prisma', 'scan-wallet.sqlite')}`
});
// Gracefully disconnect Prisma when app is closing
app.on('before-quit', async () => {
    await prisma.$disconnect()
})
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit()
}

let mainWindow: BrowserWindow

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        center: true,
        webPreferences: {
            contextIsolation: true,
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true,
        },
        width: 1280,
        height: 720,
        icon: './src/favicon.ico',
    })

    mainWindow.setMenuBarVisibility(false)

    mainWindow.maximize()

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)
    ipcMain.on('open-link', (event, url) => {
        shell.openExternal(url)
    })

    ipcMain.on('set-progress-bar', (event, value) => {
        mainWindow.setProgressBar(value)
    })

    ipcMain.handle('sheets:check', async (event, wallet: string, contractAddress: string, tokenAddress: string) => {
        try {
            const existingContract = await prisma.scanContract.findFirst({
                where: {
                    wallet: wallet.toLowerCase(),
                    contract: contractAddress,
                    token: tokenAddress,
                },
            })
            return !!existingContract
        } catch (err: any) {
            mainWindow.webContents.send('message', `Lỗi kiểm tra ví ${wallet}: ${err.message}`)
            console.error('Database Error:', err.message)
            return true
        }
    })

    ipcMain.handle('sheets:read', async (event, tokenAddress: string, contractAddress: string) => {
        try {
            const contracts = await prisma.scanContract.findMany({
                where: {
                    token: tokenAddress,
                    contract: contractAddress,
                    isAirdrop: false,
                },
                select: {
                    wallet: true,
                },
            })
            return contracts.map(c => c.wallet.toLowerCase())
        } catch (err: any) {
            mainWindow.webContents.send('message', `Lỗi đọc danh sách ví: ${err.message}`)
            console.error('Database Read Error:', err.message)
            return []
        }
    })
    ipcMain.handle('sheets:save', async (event, tokenAddress: string, contractAddress: string) => {
        try {
            const contracts = await prisma.scanContract.findMany({
                where: {
                    token: tokenAddress,
                    contract: contractAddress,
                },
                orderBy: {
                    createdAt: 'asc',
                },
            })


            const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
                title: 'Lưu file CSV',
                defaultPath: path.join(app.getPath('desktop'), `${[tokenAddress ? `t_${tokenAddress}` : '', contractAddress ? `ct_${contractAddress}` : ''].filter(Boolean).join('_')}.csv`),
                filters: [{ name: 'CSV Files', extensions: ['csv'] }],
            })

            if (canceled || !filePath) return null

            // Create CSV content
            const headers = 'Wallet,Balance,TokenBalance,IsAirdrop,CreatedAt\n'
            const rows = contracts.map(c =>
                `${c.wallet},${c.balance},${c.token || ''},${c.isAirdrop},${c.createdAt.toISOString()}`
            ).join('\n')

            fs.writeFileSync(filePath, headers + rows, 'utf8')
            return filePath
        } catch (err: any) {
            mainWindow.webContents.send('message', `Lỗi lưu file: ${err.message}`)
            console.error('Database save Error:', err.message)
            return ''
        }
    })

    ipcMain.handle('sheets:write', async (event, tokenAddress: string, contractAddress: string, ...wallets: string[]) => {
        try {
            for (const walletCombined of wallets) {
                if (!walletCombined) continue
                const [wallet, balance, tokens, airdropped] = walletCombined.split(',')

                // Check if record exists
                const existingContract = await prisma.scanContract.findFirst({
                    where: {
                        wallet: wallet.toLowerCase(),
                        token: tokenAddress,
                        contract: contractAddress
                    },
                })

                if (existingContract) {
                    // Update existing record
                    await prisma.scanContract.update({
                        where: { id: existingContract.id },
                        data: {
                            balance: Number.parseFloat(balance) || 0,
                            isAirdrop: airdropped?.toLowerCase() === 'true',
                        },
                    })
                } else {
                    // Create new record
                    await prisma.scanContract.create({
                        data: {
                            wallet: wallet.toLowerCase(),
                            contract: contractAddress,
                            balance: Number.parseFloat(balance) || 0,
                            token: tokenAddress,
                            isAirdrop: airdropped?.toLowerCase() === 'true',
                        },
                    })
                }
            }
            return true
        } catch (err: any) {
            mainWindow.webContents.send('message', `Lỗi ghi ví: ${err.message}`)
            console.error('Database Write Error:', err.message)
            return false
        }
    })

    ipcMain.handle(
        'sheets:writeBalance',
        async (_event, wallet: string, token: string, balance: string) => {
            try {
                // Check if record exists
                const existingBalance = await prisma.scanBalance.findFirst({
                    where: {
                        wallet: wallet.toLowerCase(),
                        token: token,
                    },
                })

                if (existingBalance) {
                    // Update existing record
                    await prisma.scanBalance.update({
                        where: { id: existingBalance.id },
                        data: {
                            balance: Number.parseFloat(balance) || 0,
                        },
                    })
                } else {
                    // Create new record
                    await prisma.scanBalance.create({
                        data: {
                            wallet: wallet.toLowerCase(),
                            token: token,
                            balance: Number.parseFloat(balance) || 0,
                        },
                    })
                }

                return { success: true }
            } catch (err: any) {
                mainWindow.webContents.send('message', `Lỗi ghi số dư ví ${wallet}: ${err.message}`)
                console.error('Database WriteBalance Error:', err.message)
                return { success: false, error: err.message }
            }
        }
    )

    ipcMain.handle('get-memory-info', async () => {
        const infor = await process.getProcessMemoryInfo()
        return {
            ...infor,
            appPath: app.getAppPath(),
        }
    })

    const ses = mainWindow.webContents.session
    ses.clearAuthCache()
    ses.clearCache()
    ses.clearHostResolverCache()
    mainWindow.webContents.clearHistory()
    // Open the DevTools.
    // mainWindow.webContents.openDevTools();
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow()
    }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
