import { BrowserWindow, app, ipcMain, shell } from 'electron'
import { google } from 'googleapis'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

const SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
const SPREADSHEET_ID = '1CA-R8odLmCRzEnDXeuEOWSdNqfnLT0aUB-fmeuiWdAs'

async function getSheets() {
    const auth = new google.auth.GoogleAuth({
        credentials: {
            type: 'service_account',
            project_id: 'scan-470111',
            private_key_id: 'fb99544feae77bafc880c230b95c24de3d7275c8',
            private_key:
                '-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDAlcN3hRnIAhn/\nrH1FZqRu/08u9qGmt+V+zzHSbN7HoG+lsLKKXsXMT0vc4AKZiuYiNsy3iV5Vn93K\n4vFkwKn7rpofhWmj1RFn0D1+8+/QLHiuPS9SYI14yKhsnW3KqZRc0OU8duQCmBNQ\nTrq2TSPuVHQmIZmCP7Bdo4cwFIelK2DpXBjd3jLXOHYdIan0nIFbheXwMJsiofb9\n9EGunlsPCIM9EY51QlEaegFoeye1VFl1tRMfI81/awt/K3dhH2pZ+GiE+nyKfFry\n96i3zXgh0zJgytJcvzdveSwUKrhqjqyumeY0pKscueIGWjvcKE+ib2z2IkAcJUiH\nWT45UDqJAgMBAAECggEADaOEb00trKpWAeDvf/JP9gPZ5CzXi1PHAWgxm4IfKyqj\nr9AjSWCC2m4AW4kcoXNipczMAUwWxKAtU6QCjeOp+Gt1jDmlQ3dyvx1AJIdfepaS\niV60xRiWQyhD6vwhfWTtX1FiPz6wPtrI2RZqRvciu916bOBS24Igmho2zuMHmxPL\n/p9g/6V/o2rURzXQ+buzf1WJuS/H2+fyhNRPWtdM5ajQ4BvNwrunMsiQRfFFyFs+\n0Uq+0HyMnO819haYBjGez267O7BGP62vdosH5aDulR9FCJzz8Y1a4SplWM0GO5qw\nFBpU4qBfmkGA6Q27ZxsiAwXG/sxaUEsJO7/JWCcYLQKBgQDt8PcVdqquaFRuP1Rh\nHrKfnqltp8r59tFAkJecuaZXuPAqfbF59QJGn2i9TEOFCv8TeXNgdoL51KJg5Qh9\nGRFFFIqkxa3olCNn4Jltwn6SDPxhvuPOLCDIh09/jFdqv0vwAchfjwbU3xgpAzaY\ni9P7Pf1JKf5wTN3GyiRKpAXbNwKBgQDPM469qNOZX7Zmq+UuUm3QE9+iYAAFDepA\nJKqWRNbu5hxF0StbaUw3/CPwA9TXK/l1bCGrW3eMTHOEdtI6s3ExGnqQU1YlsqpY\ngkU6TKOl2hTPlUGj7bpz79aMKoa+UgFMezOiqUQrltq26MEiNzQQahlqJ2/wLMhr\nW22LoY74PwKBgQCiXaktw1FLPDRJGvwIXftEAu/YvQQ8OFmoNkLPFrxU5gU06Zqe\n/zrzWDoP2qfEdLGE535818IemyPG/OMjAmUPf6nwMFiw+c2DR/dKt8rI/QWH6cvn\n16LzU6pC/lB0rl8yQvUpiB8ASdBhxCiQRfJ8Yluhfn96wGkiCrRjHrREVwKBgQC0\n+qiT+lGQZqxwM3aDplXqaGFud4Gs6IGSMzSY+lnt4yoQxWmkd22ufNp6+y2+H9fN\ne3xRKxxZfDFuI0bvJOsaY7FoPJJDbTIjCu4ixOwvojOJOSpTYAL63yM73K1CsWgX\nAImSa1xy4ln5Z4XCOAuOxs2aDgZU9xi7xOkDDENPiwKBgFK22s0YdJ6/bHOX7ina\nl5xqR85EBf+8MmMrbalkRDZFV4KFzXwRavHWz/doUvC5gxnLQW1C4vcYw0GF+Skl\nPqYvQEwsTnHds2wj1IqPYbBCZ5+cubNjiXDeQgpPntBXLUbTspdWrMWgTj88zhgn\n9Qa3gHtmHKjJ3CvcFbmW91gB\n-----END PRIVATE KEY-----\n',
            client_email: 'scan-781@scan-470111.iam.gserviceaccount.com',
            client_id: '105504851015285529414',
            universe_domain: 'googleapis.com',
        },
        scopes: SCOPES,
    })
    return google.sheets({ version: 'v4', auth })
}

async function ensureSheetExists(sheetTitle: string) {
    const sheets = await getSheets()

    // 1. Get spreadsheet metadata
    const metadata = await sheets.spreadsheets.get({
        spreadsheetId: SPREADSHEET_ID,
    })

    const exists = metadata.data.sheets?.some((s) => s.properties?.title === sheetTitle)

    if (!exists) {
        console.log(`Sheet '${sheetTitle}' not found -> creating...`)
        await sheets.spreadsheets.batchUpdate({
            spreadsheetId: SPREADSHEET_ID,
            requestBody: {
                requests: [
                    {
                        addSheet: {
                            properties: {
                                title: sheetTitle,
                            },
                        },
                    },
                ],
            },
        })
        console.log(`Sheet '${sheetTitle}' created successfully ✅`)
    } else {
        console.log(`Sheet '${sheetTitle}' already exists ✅`)
    }
}
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit()
}

let mainWindow: BrowserWindow

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        center: true,
        webPreferences: {
            contextIsolation: true,
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
        width: 1280,
        height: 720,
        icon: './src/favicon.ico',
    })

    mainWindow.setMenuBarVisibility(false)

    mainWindow.maximize()

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

    ipcMain.on('open-link', (event, url) => {
        shell.openExternal(url)
    })

    ipcMain.on('set-progress-bar', (event, value) => {
        mainWindow.setProgressBar(value)
    })

    ipcMain.handle('sheets:check', async (event, wallet: string, tokenAddress: string) => {
        try {
            const sheets = await getSheets()
            await ensureSheetExists(tokenAddress)
            // Range: lấy cột A từ dòng 1 đến hết (ví dụ A:A)
            const range = `'${tokenAddress}'!A:A`
            const res = await sheets.spreadsheets.values.get({
                spreadsheetId: SPREADSHEET_ID,
                range,
            })
            const values = res.data.values || []
            // Flatten để dễ check
            const addresses = values.map((row) => row[0]?.toLowerCase())
            const exists = addresses.includes(wallet.toLowerCase())
            return exists
        } catch (err) {
            console.error('Google Sheets Error:', err.message)
            return true
        }
    })

    ipcMain.handle('sheets:read', async (event, tokenAddress: string) => {
        try {
            const sheets = await getSheets()
            await ensureSheetExists(tokenAddress)
            // Lấy cả 3 cột: A (Wallet), B (Balance), C (Airdropped)
            const range = `'${tokenAddress}'!A:C`

            const res = await sheets.spreadsheets.values.get({
                spreadsheetId: SPREADSHEET_ID,
                range,
            })

            const values = res.data.values || []
            // Convert thành object và filter theo Airdropped === TRUE
            const wallets = values
                .map((row) => ({
                    address: row[0]?.toLowerCase() || '',
                    balance: row[1] ? Number(row[1]) : 0,
                    airdropped: row[2]?.toLowerCase() === 'true',
                }))
                .filter((w) => w.airdropped)

            return wallets
        } catch (err: any) {
            console.error('Google Sheets Read Error:', err.message)
            return []
        }
    })

    ipcMain.handle(
        'sheets:write',
        async (
            event,
            tokenAddress: string,
            wallet: string,
            balance: string,
            airdropped: string
        ) => {
            try {
                const sheets = await getSheets()

                await ensureSheetExists(tokenAddress)
                const range = `'${tokenAddress}'!A:C`

                // Lấy tất cả dữ liệu cột A-C
                const res = await sheets.spreadsheets.values.get({
                    spreadsheetId: SPREADSHEET_ID,
                    range,
                })

                const values = res.data.values || []
                let rowIndex = -1

                // Tìm dòng có địa chỉ ví trùng
                for (let i = 0; i < values.length; i++) {
                    if (values[i][0]?.toLowerCase() === wallet.toLowerCase()) {
                        rowIndex = i
                        break
                    }
                }

                if (rowIndex >= 0) {
                    // Đã tồn tại -> Update lại dòng (Google Sheets index bắt đầu từ 1)
                    const updateRange = `'${tokenAddress}'!A${rowIndex + 1}:C${rowIndex + 1}`

                    await sheets.spreadsheets.values.update({
                        spreadsheetId: SPREADSHEET_ID,
                        range: updateRange,
                        valueInputOption: 'RAW',
                        requestBody: {
                            values: [[wallet, balance, airdropped]],
                        },
                    })
                } else {
                    // Chưa có -> Append thêm dòng mới
                    await sheets.spreadsheets.values.append({
                        spreadsheetId: SPREADSHEET_ID,
                        range,
                        valueInputOption: 'RAW',
                        insertDataOption: 'INSERT_ROWS',
                        requestBody: { values: [[wallet, balance, airdropped]] },
                    })
                }

                return true
            } catch (err: any) {
                console.error('Google Sheets Write Error:', err.message)
                return false
            }
        }
    )

    ipcMain.handle(
        'sheets:writeBalance',
        async (_event, wallet: string, token: string, balance: string) => {
            const sheets = await getSheets()
            const today = new Date().toISOString().slice(0, 10)
            const sheetName = `Balance_${today}`
            await ensureSheetExists(sheetName)
            try {
                // 1. Lấy toàn bộ sheet
                const res = await sheets.spreadsheets.values.get({
                    spreadsheetId: SPREADSHEET_ID,
                    range: `${sheetName}!A:Z`,
                })

                const values = res.data.values || []
                if (values.length === 0) {
                    // tạo header mới nếu sheet rỗng
                    values.push(['Wallet', token])
                }

                // Header (hàng 1)
                const headers = values[0]
                let tokenCol = headers.indexOf(token)

                // Nếu chưa có cột token => thêm
                if (tokenCol === -1) {
                    headers.push(token)
                    tokenCol = headers.length - 1

                    await sheets.spreadsheets.values.update({
                        spreadsheetId: SPREADSHEET_ID,
                        range: `${sheetName}!1:1`,
                        valueInputOption: 'RAW',
                        requestBody: { values: [headers] },
                    })
                }

                // 2. Tìm row của wallet
                let rowIndex = values.findIndex((row, idx) => idx > 0 && row[0] === wallet)

                if (rowIndex === -1) {
                    // Nếu chưa có wallet → thêm dòng mới
                    rowIndex = values.length
                    const newRow = Array(headers.length).fill('')
                    newRow[0] = wallet
                    newRow[tokenCol] = balance

                    await sheets.spreadsheets.values.append({
                        spreadsheetId: SPREADSHEET_ID,
                        range: `${sheetName}!A:A`,
                        valueInputOption: 'RAW',
                        requestBody: { values: [newRow] },
                    })
                } else {
                    // Nếu đã có wallet → update balance
                    const cell = `${sheetName}!${String.fromCharCode(65 + tokenCol)}${rowIndex + 1}`
                    await sheets.spreadsheets.values.update({
                        spreadsheetId: SPREADSHEET_ID,
                        range: cell,
                        valueInputOption: 'RAW',
                        requestBody: { values: [[balance]] },
                    })
                }

                return { success: true }
            } catch (err: any) {
                console.error('Google Sheets WriteBalance Error:', err.message)
                return { success: false, error: err.message }
            }
        }
    )

    const ses = mainWindow.webContents.session
    ses.clearAuthCache()
    ses.clearCache()
    ses.clearHostResolverCache()
    mainWindow.webContents.clearHistory()
    // Open the DevTools.
    // mainWindow.webContents.openDevTools();
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow()
    }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
